plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/rioredwards/dev-archive/error-affirmations/VSCode-Affirmations-Web-Frontend"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]